spring:
  kafka:
    bootstrap-servers: localhost:9092
    client-id: test-client
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: au.com.rma.test.kafka.MessageDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: au.com.rma.test.kafka.MessageSerializer
